# ワークフローの名前
name: Google Chat Notification

# ワークフローが実行されるタイミング
on:
  # mainブランチ以外へのプッシュをトリガーにする
  push:
    branches-ignore:
      - 'main'

# 実行されるジョブ
jobs:
  notify:
    # 実行環境
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Google Chat
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{ "text": "課題が提出されました！\nリポジトリ: ${{ github.repository }}\nブランチ: `${{ github.ref_name }}`\n提出者: `${{ github.actor }}`\nコミットを確認: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" }' \
            "${{ secrets.CHAT_WEBHOOK_URL }}"