name: Notify GAS on push

on:
  push:
    branches: ["*"] # 任意のブランチにpushしたら通知
  workflow_dispatch: # 手動実行も可

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: POST GitHub event payload to GAS
        run: |
          curl -sS -X POST "https://script.google.com/macros/s/AKfycbxLB5zeSmnjqkCoutfjCrY2IRtE9rgc8bbDUDqhA6x0PECYF26gZbjTw6EPK4UWniE8/exec" \
               -H "Content-Type: application/json" \
               -d @"$GITHUB_EVENT_PATH"
